### ISSUE TITLE
Комментарии по схеме

### ISSUE THREAD

**Issue by kharvd** [paknikolay/DBProject#2]
1. Что такое Teachers в таблице Subjects, если есть таблица Teacher_Subject?
2. Зачем два раза связь Teachers и Subjects: через таблицы Teacher_Subject и Schedule?
3. Для таблиц Chair, Subjects, Department, Schedule добавить суррогатные ключи
4. В Chair можно хранить завкафа.
5. Что такое Date_Of_Enrollment и почему оно bigint?
6. Lecture/seminar -- у названия колонки не должно быть странных символов. Кроме лекций и семинаров бывают лабы.
7. Зачем DepartmentChair? Может ли у кафедры быть два факультета?

**Comment by paknikolay** [comment]
1) Убрано поле в таблице Subject
2) Удалена таблица Teacher_Subject
3) Добавлено и исправлено
4) Добавлено
5) дата поступления в ВУЗ bigint, потому что опечатка
6)Исправлено на обобщенное название)
7) Да, есть общие для нескольких факультетов кафедры(Вышмат)

**Comment by kharvd** [comment]
8. Может ли студент быть одновременно также преподавателем? Если да, нужно выделить общую информацию из таблиц Teachers и Student.
9. Address, Departure_name -- орфография
10. Почему специализация bigint?

**Comment by paknikolay** [comment]
8) исправили, к преподавателям ещё добавим поля
9) Address исправлено, но DEPARTMENT is correct - факультет DEPARTUE - отправление
10) не знаю, имелось ввиду Бакалавриат/Магистр, переименовал в Degree

**Comment by kharvd** [comment]
9. Departure_ID -- "ID отправления". Должно быть Department_ID всё-таки.
10. Можно сделать отдельную таблицу Degrees и добавить туда три записи с суррогатными ключами: Бакалавр, Магистр, Специалист. Ссылаться на неё через суррогатный ключ.

**Comment by paknikolay** [comment]
9) согласен
10) Добавлено

**Comment by kharvd** [comment]
Ок, тогда пока норм.
